# Build stage
FROM node:22 AS build

WORKDIR /app
COPY . .

RUN npm ci
RUN npm run build

# Production stage
FROM python:3.13

WORKDIR /app

COPY . .
COPY --from=build /app/frontend/build/ ./frontend/build/

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 80

CMD ["deployment/entrypoint.sh", "-w"]
